<?php	
	$qquery = "SELECT *
		FROM MDS_INFO
		INNER JOIN USER_PLANS
		ON USER_PLANS.BSC_EMPLID = MDS_INFO.BSC_EMPLID
		INNER JOIN DEPARTMENTS
		ON USER_PLANS.DEPT_ID = DEPARTMENTS.DEPARTMENT_ID
		INNER JOIN BUSINESS_UNIT
		ON BUSINESS_UNIT.BUSINESS_UNIT_ID = USER_PLANS.BUSINESS_UNIT_ID
		WHERE MDS_INFO.BSC_EMPLID LIKE '%{SEARCH_STRING}%' 
		OR  MDS_INFO.FIRST_NAME LIKE '%{SEARCH_STRING}%'  
		OR  USER_PLANS.BUSINESS_UNIT_ID LIKE '%{SEARCH_STRING}%'  
		OR  USER_PLANS.DEPT_ID LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.JOBCODE LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.JOBCODE_DESCR LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.POSITION_NBR LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.POSNUM_DESCR LIKE '%{SEARCH_STRING}%' 
		ORDER BY MDS_INFO.BSC_EMPLID DESC 
		OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY";

/*****

We need a function that accep follwing parameter 
1) SEARCH_STRING  // like id or name or department
2) ORDER_BY_COLUMN_NAME // like MDS_INFO.BSC_EMPLID, MDS_INFO.FIRST_NAME
3) ORDER_BY_TYPE // DESC or ASC
4) OFFSET  // 0
5) NO_OF_ROWS  // 10


if possible return total number of affected rows

*****/

function get_Users(SEARCH_STRING, ORDER_BY_COLUMN_NAME, ORDER_BY_TYPE, OFFSET, NO_OF_ROWS){
	"SELECT *
		FROM MDS_INFO
		INNER JOIN USER_PLANS
		ON USER_PLANS.BSC_EMPLID = MDS_INFO.BSC_EMPLID
		INNER JOIN DEPARTMENTS
		ON USER_PLANS.DEPT_ID = DEPARTMENTS.DEPARTMENT_ID
		INNER JOIN BUSINESS_UNIT
		ON BUSINESS_UNIT.BUSINESS_UNIT_ID = USER_PLANS.BUSINESS_UNIT_ID
		WHERE MDS_INFO.BSC_EMPLID LIKE '%{SEARCH_STRING}%' 
		OR  MDS_INFO.FIRST_NAME LIKE '%{SEARCH_STRING}%'  
		OR  USER_PLANS.BUSINESS_UNIT_ID LIKE '%{SEARCH_STRING}%'
		OR  USER_PLANS.DEPT_ID LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.JOBCODE LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.JOBCODE_DESCR LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.POSITION_NBR LIKE '%{SEARCH_STRING}%'  
		OR  MDS_INFO.POSNUM_DESCR LIKE '%{SEARCH_STRING}%' 
		ORDER BY {ORDER_BY_COLUMN_NAME} {ORDER_BY_TYPE}
		OFFSET {OFFSET} ROWS FETCH NEXT {NO_OF_ROWS} ROWS ONLY"
}



	


